version: '3.8'
services:
  db:
    image: postgres:15
    container_name: krakenbet-db
    environment:
      POSTGRES_DB: krakenbet
      POSTGRES_USER: kraken
      POSTGRES_PASSWORD: kraken123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
